### ISSUE TITLE
Field check returns an error even when the default value is not provided

### ISSUE THREAD

**Issue by seroy** [loggi/python-choicesenum#169] opened 2019-04-26 09:17 UTC
* Choices Enum version: 0.5.3

### Description

Field check returns an error even when the default value is not provided. So currently is no way to not specify a default value in case when field must don't have default value and value must be always provided obviously.

**Comment by fgmacedo** [comment] 2019-09-05 21:05
Hi @seroy , this decision is by design. With the current implementation there's no way to the enum field hold a value that is not an Enum member. To the value should allways be an enum member, is a non-nullable API. 

See: https://github.com/loggi/python-choicesenum/blob/master/README.rst#fields

> Is guaranteed that the field value is always a ChoicesEnum item. Pay attention that the field will only accept valid values for the Enum in use, so if your field allow null, your enum should also

I'll close the issue for now, please fell free to reopen it if you like to discuss this further.

**Closed by fgmacedo** 2019-09-05 21:05 UTC

**Comment by seroy** [comment] 2019-09-10 15:26
Hi @fgmacedo 
Thanks for response. Could you please explain why we need to require default value for this case:

<pre>
class ColorModel(models.Model):
    color = EnumCharField(
        max_length=100,
        enum=Colors,
        <b>null=False</b>
    )
</pre>
Why we need pre-select some values in the forms, etc?
For me it seems like bug, what the point?
